# Generated by scripts/render-homebrew-formula.sh; do not edit by hand.
class Babysit < Formula
  desc "Watch pull requests and merge requests for CI status and bot review findings"
  homepage "https://github.com/volker48/babysit"
  version "1.0.2"
  license "MIT"

  depends_on :macos

  on_arm do
    url "https://github.com/volker48/babysit/releases/download/v1.0.2/babysit-v1.0.2-aarch64-apple-darwin.tar.gz"
    sha256 "c1a62fd785bf0dff8d3b5413ea60aeeb91fe5c9aecbe8819dc7ddee0a3b77e63"
  end

  on_intel do
    url "https://github.com/volker48/babysit/releases/download/v1.0.2/babysit-v1.0.2-x86_64-apple-darwin.tar.gz"
    sha256 "86cbd70cfdf0c649edd5e0532e59b18dc7ae8c2eb78c68648f69b049ba98b719"
  end

  def install
    bin.install "babysit"
  end

  def caveats
    <<~EOS
      babysit shells out to an authenticated forge CLI:
        GitHub: brew install gh && gh auth login
        GitLab: brew install glab && glab auth login
    EOS
  end

  test do
    assert_equal "babysit #{version}", shell_output("#{bin}/babysit --version").strip
  end
end
