#!/usr/bin/env bash
# Renders Formula/babysit.rb for a published release.
#
# Usage: scripts/render-homebrew-formula.sh <version> <SHA256SUMS file>
# The SHA256SUMS file is the one attached to the GitHub release.
set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <version> <SHA256SUMS>" >&2
  exit 2
fi

version="${1#v}"
sums="$2"

checksum() {
  local archive="babysit-v${version}-$1.tar.gz"
  local sum
  sum="$(awk -v name="$archive" '$2 == name { print $1 }' "$sums")"
  if [ -z "$sum" ]; then
    echo "missing checksum for $archive in $sums" >&2
    exit 1
  fi
  printf '%s' "$sum"
}

arm_sha="$(checksum aarch64-apple-darwin)"
intel_sha="$(checksum x86_64-apple-darwin)"
base="https://github.com/volker48/babysit/releases/download/v${version}"

cat <<RUBY
# Generated by scripts/render-homebrew-formula.sh; do not edit by hand.
class Babysit < Formula
  desc "Watch pull requests and merge requests for CI status and bot review findings"
  homepage "https://github.com/volker48/babysit"
  version "${version}"
  license "MIT"

  depends_on :macos

  on_arm do
    url "${base}/babysit-v${version}-aarch64-apple-darwin.tar.gz"
    sha256 "${arm_sha}"
  end

  on_intel do
    url "${base}/babysit-v${version}-x86_64-apple-darwin.tar.gz"
    sha256 "${intel_sha}"
  end

  def install
    bin.install "babysit"
  end

  def caveats
    <<~EOS
      babysit shells out to an authenticated forge CLI:
        GitHub: brew install gh && gh auth login
        GitLab: brew install glab && glab auth login
    EOS
  end

  test do
    assert_equal "babysit #{version}", shell_output("#{bin}/babysit --version").strip
  end
end
RUBY
